# Generated by Django 3.1.7 on 2021-05-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionForAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Цифры,знаки', max_length=20, verbose_name='Значение параметра')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legend.parameter', verbose_name='Параметр запроса')),
            ],
            options={
                'verbose_name': 'Пара параметр-значение',
                'verbose_name_plural': 'Пары параметр-значение',
            },
        ),
        migrations.CreateModel(
            name='RequestForApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=150, verbose_name='Адрес для API запросов')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
                ('parameters', models.ManyToManyField(blank=True, to='api_requests.OptionForAPI', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Запрос для внешней БД',
                'verbose_name_plural': 'Запросы для внешней БД',
            },
        ),
    ]
