# Generated by Django 3.1.7 on 2021-06-22 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionForAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Цифры,знаки', max_length=20, verbose_name='Значение параметра')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legend.parameter', verbose_name='Параметр запроса')),
            ],
            options={
                'verbose_name': 'Пара параметр-значение',
                'verbose_name_plural': 'Пары параметр-значение',
            },
        ),
        migrations.CreateModel(
            name='RequestForApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=150, verbose_name='Адрес для API запросов')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
                ('parameters', models.ManyToManyField(blank=True, to='api_requests.OptionForAPI', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Запрос для внешней БД',
                'verbose_name_plural': 'Запросы для внешней БД',
            },
        ),
        migrations.CreateModel(
            name='CompilationR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_code', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_code', to='legend.parameter', verbose_name='Запрос кода')),
                ('get_current_page_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_current_page_number', to='legend.attribute', verbose_name='Текущий номер страницы в теле ответа')),
                ('get_data', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_data', to='legend.attribute', verbose_name='Данные со страницы')),
                ('get_page', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_page', to='legend.parameter', verbose_name='Запрос страницы')),
                ('get_page_count', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_page_count', to='legend.attribute', verbose_name='Общее количество страниц в теле ответа')),
                ('get_record_count', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_record_count', to='legend.attribute', verbose_name='Общее количество записей в теле ответа')),
                ('initial_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_requests.requestforapi', verbose_name='Главный запрос')),
            ],
            options={
                'verbose_name': 'Сборник запросов для скачивания БД',
                'verbose_name_plural': 'Сборники запросов для скачивания БД',
            },
        ),
    ]
