# Generated by Django 3.1.7 on 2021-05-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionForParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_of_db', models.CharField(choices=[('Budget', 'Справочник бюджетов'), ('GlavBudgetClass', 'Справочник главы по бюджетной классификации')], help_text='Выбор результирующей модели', max_length=60, verbose_name='Модель для заполнения')),
                ('field_in_model', models.CharField(choices=[('Budget| Справочник бюджетов', (('id', 'id| ID'), ('guid', 'guid| Глобально-уникальный идентификатор записи'), ('code', 'code| Код'), ('name', 'name| Полное наименование'), ('parentcode', 'parentcode| Вышестоящий бюджет'), ('startdate', 'startdate| Дата начала действия записи'), ('enddate', 'enddate| Дата окончания действия записи'), ('status', 'status| Статус записи'), ('budgettype', 'budgettype| Тип бюджета'))), ('GlavBudgetClass| Справочник главы по бюджетной классификации', (('id', 'id| ID'), ('guid', 'guid| Глобально-уникальный идентификатор записи'), ('code', 'code| Код'), ('name', 'name| Сокращенное наименование'), ('startdate', 'startdate| Дата начала действия записи'), ('enddate', 'enddate| Дата окончания действия записи'), ('budget', 'budget| Бюджет'), ('dateinclusion', 'dateinclusion| Дата включения кода'), ('dateexclusion', 'dateexclusion| Дата исключения кода'), ('year', 'year| Год')))], help_text='Не перепутайте поле модели', max_length=60, verbose_name='Поле модели для заполнения')),
                ('description', models.CharField(blank=True, max_length=140, verbose_name='Описание')),
                ('field_in_json', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='legend.attribute', verbose_name='Поле в JSON')),
            ],
            options={
                'verbose_name': 'Параметр сериализвтора',
                'verbose_name_plural': 'Параметры сериализвтора',
            },
        ),
        migrations.CreateModel(
            name='ParserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
                ('options', models.ManyToManyField(to='own_parsers.OptionForParser', verbose_name='Параметры для сериализатора')),
            ],
            options={
                'verbose_name': 'Конфигурация сериализатора для заполнения БД',
                'verbose_name_plural': 'Конфигурации сериализатора для заполнения БД',
            },
        ),
    ]
