# Generated by Django 3.1.7 on 2021-07-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('code', 'startdate', 'enddate')},
        ),
    ]
