# Generated by Django 3.1.7 on 2021-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0002_auto_20210701_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='code',
            field=models.CharField(default=None, max_length=8, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='enddate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата окончания действия записи'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='startdate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата начала действия записи'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('code', 'startdate')},
        ),
    ]
