# Generated by Django 3.1.7 on 2021-07-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0003_auto_20210706_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('code', 'startdate', 'enddate')},
        ),
    ]
