# Generated by Django 3.1.7 on 2021-07-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0004_auto_20210706_1118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('code', 'startdate')},
        ),
    ]
