# Generated by Django 3.1.7 on 2021-07-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0005_auto_20210706_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='guid',
            field=models.CharField(max_length=36, unique=True, verbose_name='Глобально-уникальный идентификатор записи'),
        ),
    ]
