# Generated by Django 3.1.7 on 2021-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0006_auto_20210708_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='filedate',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата создания записи(файла)'),
        ),
        migrations.AddField(
            model_name='budget',
            name='loaddate',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата загрузки записи(файла)'),
        ),
        migrations.AddField(
            model_name='budget',
            name='okatocode',
            field=models.CharField(blank=True, help_text='Общероссийский классификатор объектов административно-территориального деления https://classifikators.ru/okato', max_length=11, verbose_name='Код ОКАТО'),
        ),
        migrations.AddField(
            model_name='budget',
            name='oktmocode',
            field=models.CharField(blank=True, help_text='Общероссийский классификатор территорий муниципальных образований (сокращ. ОКТМО) — классификатор объектов административно-территориального деления Российской Федерации, входит в состав «Единой системы классификации и кодирования технико-экономической и социальной информации Российской Федерации» (ЕСКК). https://oktmorus.ru', max_length=11, verbose_name='Код ОКТМО'),
        ),
        migrations.AddField(
            model_name='budget',
            name='tofkcode',
            field=models.CharField(blank=True, help_text='Территориальный орган Федерального казначейства', max_length=4, verbose_name='Код ТОФК'),
        ),
    ]
